### ISSUE TITLE
App still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [frodoking/GithubAndroidClient#2]
With the last release and commit being 2.5 years past, I wonder whether you still maintain this app @frodoking? Will there be future releases, or is development stopped?

**Comment by frodoking** [comment]
Sorry, this project has been suspended because of no time to maintain. Thank you for your attention.

**Comment by IzzySoft** [comment]
Thanks for your reply, @frodoking! Sad to read – but life goes on… All the best for your current and future projects!
